import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar_AR': {
      "appName":"Claimizer",
      "login":"تسجيل الدخول",
      "welcomePhase":"أهلا بك في إحصائيات الملاك",
      "email":"البريد الالكتروني",
      "password":"كلمة المرور",
      'forgotPassword':"نسيت كلمة المرور؟",
      "somethingWentWrong":"حدث خطأ ما",
      "pleaseTryAgain":"من فضلك اعد المحاولة",
      "reloadScreen":"اعادة التحميل",
      "company":"اسم الشركة",
      "statisticDate":"تاريخ الاحصائيه",
      "companies":"الشركات",
      "buildingName":"اسم المبني",
      "error":"خطأ",
      "search":"بحث",
      "logOutPhase":"هل انت متاكد من تسجيل خروجك؟",
      "connectionError":"خطأ في الاتصال",
      "companyData":"بيانات الشركة",
      "sortBy":"ترتيب حسب:-",
      "name":"الاسم",
      "value":"القيمة",
      "yes":"نعم",
      "no":"لا",
      "chartWidgetPhase":"الرسوم البيانية للإحصاء",
      "landlordStatistics":"إحصائيات الملاك",
      "count":"العدد",
      "userAccounts":"ادارة الحسابات",
      "logout":"تسجيل خروج",
      "changeLanguage":"تغير اللغة",
      "welcome":"اهلا",
      "signedInPhase":"ان الان مسجل الدخول ك ",
      "invalidCredentials":"بيانات غير صحيحة",
      "ok":"موافق",
      "noData":"لا يوجد بيانات",
      "deleteAccountPhase":"هل انت متأكد من حذف هذا الحساب؟",
      "deletedAccountSuccessfully":"تم حذف الحساب بنجاح",
      "emptyEmail":"من فضلك ادخل البريد الالكتروني",
      "emptyPassword":"من فضلك ادخل كلمه المرور",
      "updatePhase":"هناك نسخة جديدة متاحة من التطبيق، يرجى تحديث التطبيق للاستمتاع بالميزات الجديدة",
      "update":"تحديث"
    },
    'en_US': {
      "appName":"Claimizer",
      "login":"Login",
      "welcomePhase":"Welcome To Landlord Statistics",
      "email":"Email",
      "password":"Password",
      'forgotPassword':"Forgot password?",
      "somethingWentWrong":"Something Went Wrong",
      "pleaseTryAgain":"Please Try Again",
      "reloadScreen":"Reload Screen",
      "company":"Company",
      "statisticDate":"Statistic Date",
      "companies":"Companies",
      "buildingName":"Building Name",
      "error":"Error",
      "search":"Search",
      "logOutPhase":"Are you sure you want to logout ?",
      "connectionError":"Connection Error",
      "companyData":"Company Data",
      "sortBy":"Sort By :-",
      "name":"Name",
      "value":"Value",
      "yes":"Yes",
      "no":"No",
      "chartWidgetPhase":"Charts For Statistics",
      "landlordStatistics":"Landlord Statistics",
      "count":"Count",
      "userAccounts":"User Accounts",
      "logout":"Logout",
      "changeLanguage":"Change Language",
      "welcome":"Welcome",
      "signedInPhase":"You are now signed in as",
      "ok":"OK",
      "noData":"There is no data",
      "deleteAccountPhase":"Are you sure you want to delete this account?",
      "deletedAccountSuccessfully":"Account has been deleted successfully",
      "emptyEmail":"Please enter your email",
      "emptyPassword":"Please enter your password",
      "updatePhase":"There is a new version of application available , please update the application to enjoy new features",
      "update":"Update"
    },
  };
}